### ISSUE TITLE
error-ex is not in the npm registry

### ISSUE THREAD

**Issue by mi251** [Qix-/node-error-ex#13]
when i run `npm i error-ex`
i get this:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2020-02-12T03_37_53_666Z-debug.log
```

Why is that ?!

**Comment by frodoe7** [comment]
I have the same issue

**Comment by ahmedqasid** [comment]
I have the same issue also, it seems many libraries are dependent on this library

**Comment by mi251** [comment]
Yes, same issue with `npm install errorhandler` !

**Comment by mi251** [comment]
i was creating a react app, it was failing with this error.
i have found a solution which is to set npm registery by running this command.
`yarn config set registry http://registry.npm.taobao.org`
you can find more here, https://classic.yarnpkg.com/en/package/webpack-genius

now creating an app is working but this command `npm install error-ex` is still failing.

**Comment by shazron** [comment]
It's failing in at least the Asia Pacific (SIN) region. I sent a support request to support@npmjs.org with these details: https://github.com/npm/cli/issues/797

**Comment by shazron** [comment]
`npm info error-ex` works in the San Jose, California region

**Comment by musabhusaini** [comment]
My short-term workaround was to add it through the git repo:
``` bash
npm install --save-dev git+https://github.com/Qix-/node-error-ex.git#3953ebb9e4a33287e67676a70a8ad72bbbe38075
```
The hash is pointing to the latest release (1.3.2) at this time, but you can modify it to match your [desired release](https://github.com/Qix-/node-error-ex/releases).

**Comment by Qix-** [comment]
Did this just start happening? I haven't touched anything on my end, nor has there been a new publish in ages.

I'll investigate, thanks for letting me know.

**Comment by Qix-** [comment]
Appears to be an issue with npm - others are reporting broken packages on StackOverflow as well.

I've submitted a support ticket and have tweeted at their support account. It'll be another several hours before we head anything - but as of right now, there has not been any advisory.

**Comment by ScarfaceIII** [comment]
> Did this just start happening? I haven't touched anything on my end, nor has there been a new publish in ages.
> 
> I'll investigate, thanks for letting me know.

Yes it just started to happen. We are even using version 1.3.1, locked from one of our cascading dependencies, but one of our pipelines failed.

**Comment by Qix-** [comment]
Yeah, sorry about that :/ Nothing I can do at the moment.

I'll keep this issue updated as I find out more.

**Comment by ScarfaceIII** [comment]
> Appears to be an issue with npm - others are reporting broken packages on StackOverflow as well.
> 
> I've submitted a support ticket and have tweeted at their support account. It'll be another several hours before we head anything - but as of right now, there has not been any advisory.

Once again, yes. It appears to be due to NPM registries, I was able to work around it with this:
` ~   npm config set registry http://registry.npm.taobao.org                                                                                                                                                               
 ~  npm i error-ex@1.3.1`
And it worked. But I cannot do that in my pipeline.

**Comment by nomadtechie** [comment]
Hi all - I work at @npm and we're very sorry about the `404`'s you are experiencing. 

We have identified the issue on our end and rolled out the fix. Unfortunately, its going take some time to propagate through all our nodes in our CDN layer.

You can follow along for progress via the [incident on our status page](https://status.npmjs.org/incidents/lvgmcrfvrvsh)

Also, you if you have other packages affected then please feel free to [contact our support team directly.](https://www.npmjs.com/support)

**Comment by mi251** [comment]
Thank you, i experienced one more package  having the same problem. `npm i errorhandler` 

please do not allow that to happen again. There can be problem in packages but not on package provider. And not for more than a day. :(

Thanks @nomadtechie

**Comment by Qix-** [comment]
> please do not allow that to happen again. There can be problem in packages but not on package provider. And not for more than a day.

Look I've got problems with npm from time to time but they're human and there's no such thing as 100% uptime. For the absurd amount of traffic they serve and the fact they are generally exceptionally transparent about outages, however minor, I think we should be okay with a few hiccups from time to time.

Further, if your production pipeline is so mission critical that you haven't allowed for any downtime of an upstream provider (I'd suggest you rethink your strategy if so) then you're welcome to set up a couchdb mirror and host your own copies of packages so npm outages do not affect you. Most large companies do this by default.

Thank you for reaching out here @nomadtechie - always appreciated.

Closing - please direct any other issues related to this incident towards npm; I cannot do anything further.

Thanks again to everyone for reporting! 😌

**Comment by jinbeeahn** [comment]
not sure if the fix from NPM has been propagated to the other region, but NA east coast (Montreal) still has the issue.

**Comment by Qix-** [comment]
@jin Give it a bit. CDNs take a while to propagate.

**Comment by mattgrande** [comment]
@nomadtechie - The status page says it's resolved, but I'm still seeing the issue. Any suggestions?

`error An unexpected error occurred: "https://registry.yarnpkg.com/error-ex/-/error-ex-1.3.2.tgz: Request failed \"404 Not Found\"".`

**Comment by grzel4000** [comment]
Still getting same error, connecting from Toronto, Canada
==
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
==

**Comment by Qix-** [comment]
> Closing - **_please direct any other issues related to this incident towards npm_**; I cannot do anything further.
