### ISSUE TITLE
Support passing an existing error to the subclassed error constructor

### ISSUE THREAD

**Issue by sindresorhus** [Qix-/node-error-ex#3]
```js
var JSONError = errorEx('JSONError');

try {
	throw Error('foo');
} catch (err) {
	throw new JSONError(err);
}
```

I'm used to doing it when creating gulp plugins: https://github.com/sindresorhus/gulp-esformatter/blob/894ead7dd5b796e26e8d3c74cdf0e4bcc55db76a/index.js#L22

https://github.com/gulpjs/gulp-util/blob/master/lib/PluginError.js

It feels more natural just passing the existing error into a function and getting a new one out, instead of mutating the error in-place.

**Comment by Qix-** [comment]
Landed in d68784c5335eb858d6573df55738fd4d98cbc14e and published as `1.2.0`.
