### ISSUE TITLE
[Question] Why error.name?

### ISSUE THREAD

**Issue by Kikobeats** [Qix-/node-error-ex#5]
Just curious, because I'm in a point of my code that I need to handle homogeneously different errors from different errors factories.

Yes, I suppose that for this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name

But is curious because node errors use `.code` field. I think that [https://github.com/rvagg/node-errno#errno-exposed](node-errno) is a very standard error handle library. He calls your `name` into `code`.

Also following this approach, instead of `JSONError` could be `EJSON`.

**Comment by Kikobeats** [comment]
Thanks for the clarification! :-)

**Comment by Qix-** [comment]
Not a problem! :+1:
